# VietMed correction: end-to-end LoRA training

Notebook thực thi R0/R1/R2 và R3 seeds 42/43/44 theo `RESEARCH_PLAN.md`; xuất model độc lập. Full mode không giới hạn mẫu. Nguồn phụ tắt khi chưa có phê duyệt; không tuyên bố an toàn y khoa.

## Khởi động từ repo root
```bash
uv python install 3.12
uv venv --python 3.12 experiments/002-vietmed-correction-training/.venv
uv pip sync --python experiments/002-vietmed-correction-training/.venv/bin/python experiments/002-vietmed-correction-training/requirements.lock --extra-index-url https://download.pytorch.org/whl/cu128
experiments/002-vietmed-correction-training/.venv/bin/python experiments/002-vietmed-correction-training/scripts/execute_notebook.py --mode full
```

Hoặc mở notebook với kernel từ môi trường trên và **Restart Kernel → Run All**. `VODOCO_PROJECT_ROOT` cấu hình root nếu notebook server chạy ngoài repo; `CORRECTION_MODE=smoke` dùng namespace riêng để gỡ lỗi, không được coi là full training.

## 1. Cấu hình và preflight
Paths được resolve từ repo, không hardcode máy cá nhân. Kiểm tra version trước khi import stack training.

In [1]:
import os, sys, importlib.metadata
from pathlib import Path

MODE = os.environ.get('CORRECTION_MODE', 'full')
if os.environ.get('VODOCO_PROJECT_ROOT'):
    PROJECT_ROOT = Path(os.environ['VODOCO_PROJECT_ROOT']).expanduser().resolve()
else:
    PROJECT_ROOT = next((p for p in [Path.cwd(), *Path.cwd().parents] if (p / 'RESEARCH_PLAN.md').is_file()), None)
if PROJECT_ROOT is None:
    raise RuntimeError('Set VODOCO_PROJECT_ROOT before launching this notebook outside the repo')
EXPERIMENT = PROJECT_ROOT / 'experiments/002-vietmed-correction-training'
if sys.version_info[:2] != (3, 12):
    raise RuntimeError('Select the pinned Python 3.12 environment described above')
for line in (EXPERIMENT / 'requirements.lock').read_text().splitlines():
    if not line or line.startswith('#') or '==' not in line:
        continue
    package, expected = line.split('==', 1)
    if importlib.metadata.version(package).lower() != expected.lower():
        raise RuntimeError(f'Environment mismatch: {package}; sync requirements.lock before starting kernel')
sys.path.insert(0, str(EXPERIMENT / 'scripts'))
from runtime import make_config, inspect_runtime, prepare_models, lock_recipe
from common import read_json, release_gpu
from data_pipeline import prepare_data, generate_asr_cache, build_pairs
from pipeline import (tuning_records, baselines, train_all, selected_dev_results, lock_final_selection, final_evaluation, export_final_model, final_summary)
from training import training_smoke
import pandas as pd
from transformers import AutoTokenizer
cfg = make_config(PROJECT_ROOT, MODE)
display({'mode': MODE, 'project_root': str(PROJECT_ROOT), 'training': cfg['training'], 'generation': cfg['generation'], 'seeds': cfg['seeds']})

/home/hieu/Work/Learning.UIT/VoDoCo/experiments/002-vietmed-correction-training/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

{'mode': 'full',
 'project_root': '/home/hieu/Work/Learning.UIT/VoDoCo',
 'training': {'rank': 16,
  'alpha': 32,
  'dropout': 0.05,
  'learning_rate': 0.0001,
  'weight_decay': 0.01,
  'max_grad_norm': 1.0,
  'warmup_ratio': 0.05,
  'batch_size': 2,
  'gradient_accumulation_steps': 8,
  'epochs': 5,
  'patience': 2,
  'errorful_fraction': 0.7},
 'generation': {'num_beams': 4, 'do_sample': False, 'max_new_tokens': 512},
 'seeds': [42, 43, 44]}

## 2. Môi trường, GPU và reproducibility
Đo CUDA GEMM + autograd thật. Pin libraries, precision, source hashes và code provenance.

In [2]:
environment = inspect_runtime(cfg)
display({k: environment[k] for k in ['python', 'libraries', 'gpu', 'gpu_total_bytes', 'compute_capability', 'cuda', 'precision', 'cuda_forward_backward_loss']})

{'python': '3.12.13',
 'libraries': {'torch': '2.8.0+cu128',
  'transformers': '4.57.6',
  'peft': '0.17.1',
  'accelerate': '1.10.1',
  'datasets': '4.1.1',
  'pyarrow': '21.0.0',
  'soundfile': '0.13.1',
  'jiwer': '4.0.0',
  'sentencepiece': '0.2.1',
  'numpy': '2.2.6',
  'scipy': '1.16.2',
  'librosa': '0.11.0',
  'huggingface-hub': '0.36.2',
  'nbclient': '0.10.2',
  'nbformat': '5.10.4',
  'ipykernel': '6.30.1'},
 'gpu': 'NVIDIA GeForce RTX 5060 Ti',
 'gpu_total_bytes': 16660430848,
 'compute_capability': [12, 0],
 'cuda': '12.8',
 'precision': 'bf16',
 'cuda_forward_backward_loss': 125.97351837158203}

## 3. Nguồn dữ liệu và split audit
Verify 16 file VietMed, decode đủ 9.207 audio và kiểm tra PCM duplicates. Giữ official test; tách recording `VietMed_019` khỏi tuning. Audio/raw reference không sửa.

In [3]:
records_by_split = prepare_data(cfg)
split_audit = read_json(Path(cfg['derived_dir']) / MODE / 'manifests/splits.json')
display(pd.DataFrame([{'split': split, 'selected_rows': len(rows), 'train_duplicate_exclusions': sum(r['duplicate_excluded'] for r in rows)} for split, rows in records_by_split.items()]))
display({'derived_counts': split_audit['derived_counts'], 'train_excluded_ids': split_audit['train_excluded_ids'], 'full_audio_audit_count': split_audit['full_audio_audit_count']})

   split  selected_rows  train_duplicate_exclusions
0  train           2773                           0
1    dev           2912                           0
2   test           3437                           0
3     cv             85                           0

{'derived_counts': {'train_real': 2773,
  'dev_tune': 2769,
  'dev_shared_recording': 143,
  'test_official': 3437,
  'cv_diagnostic': 85},
 'train_excluded_ids': [],
 'full_audio_audit_count': 9207}

## 4. Model/processor snapshots
Model/processor SHA được khóa; các file local được đối chiếu hash upstream. Không trộn PhoWhisper với MultiMed-ST.

In [4]:
models = prepare_models(cfg)
display(pd.DataFrame([{'role': kind, 'repo': value['repo_id'], 'revision': value['revision'], 'verified_files': len(value['hashes'])} for kind, value in models.items()]))

Verified asr: leduckhai/MultiMed-ST@fb15edd1dfc68810a7d0c75e6cfc73c3e5ed01c1 (11 files)

Verified correction: bmd1905/vietnamese-correction-v2@a3d342348d39d87622aa58aabd07de38ade8c17b (6 files)

Verified ner: leduckhai/VietMed-NER@cccffb7de14423114f7d4bafc9f736b9d866e446 (6 files)

,role,repo,revision,verified_files
0,asr,leduckhai/MultiMed-ST,fb15edd1dfc68810a7d0c75e6cfc73c3e5ed01c1,11
1,correction,bmd1905/vietnamese-correction-v2,a3d342348d39d87622aa58aabd07de38ade8c17b,6
2,ner,leduckhai/VietMed-NER,cccffb7de14423114f7d4bafc9f736b9d866e446,6

## 5. Cache ASR train/dev
Frozen MultiMed-ST, 16 kHz, deterministic decoding. Audio dài dùng native long-form; không crop reference. Resume chỉ khi signature, ID, reference và audio hash khớp.

In [5]:
train_records = generate_asr_cache(cfg, records_by_split['train'], 'train')
dev_all = generate_asr_cache(cfg, records_by_split['dev'], 'dev')
dev_records = tuning_records(dev_all)
release_gpu()
display({'train': len(train_records), 'dev_all': len(dev_all), 'dev_tune': len(dev_records), 'empty_train_hypotheses': sum(r['hypothesis_empty'] for r in train_records)})

`torch_dtype` is deprecated! Use `dtype` instead!

{'train': 2773, 'dev_all': 2912, 'dev_tune': 2769, 'empty_train_hypotheses': 0}

## 6. D_real và identity supervision
Hypothesis→reference chỉ từ train. Giữ errorful và identity; audit parent IDs và token lengths. Nếu dài, chia cửa sổ input/target theo alignment, không truncate độc lập.

In [6]:
tokenizer = AutoTokenizer.from_pretrained(cfg['models']['correction']['path'], local_files_only=True)
pairs = build_pairs(cfg, train_records, tokenizer)
pair_audit = read_json(Path(cfg['derived_dir']) / MODE / 'pairs/manifest.json')
display({k: pair_audit[k] for k in ['eligible_parent_count', 'pair_count', 'pair_type_counts', 'errorful_pairs', 'real_errorful_parents', 'identity_unique_views', 'windowed_views', 'source_token_max', 'target_token_max']})

{'eligible_parent_count': 2773,
 'pair_count': 5544,
 'pair_type_counts': {'real': 2773, 'identity': 2771},
 'errorful_pairs': 541,
 'real_errorful_parents': 541,
 'identity_unique_views': 2771,
 'windowed_views': 0,
 'source_token_max': 44,
 'target_token_max': 44}

## 7. Baseline và evaluation
R0 không sửa; R1 train-only rules có provenance; R2 zero-shot. Khóa review sample trước corrector outputs. Corpus WER giữ insertion của empty reference; preservation là probe, không phải clinical safety.

In [7]:
baseline_result = baselines(cfg, train_records, dev_records)
display(pd.DataFrame([{'run': run, 'wer': report['summary']['wer'], 'cer': report['summary']['cer'], 'overcorrection': report['summary']['reference_overcorrection_rate']} for run, report in baseline_result['reports'].items()]))

{
  "R0": {
    "wer": 0.04436209473266844,
    "preservation": 0.0
  },
  "R1": {
    "wer": 0.04436209473266844,
    "preservation": 0.0
  },
  "R2": {
    "wer": 0.05247506633726782,
    "preservation": 0.19934994582881907
  }
}

  run       wer       cer  overcorrection
0  R0  0.044362  0.035780         0.00000
1  R1  0.044362  0.035780         0.00000
2  R2  0.052475  0.042811         0.19935

## 8. Training smoke: gradients, cập nhật, save/load
Hai optimizer updates trên train thật, tách khỏi các lượt chính. Chứng minh base frozen, adapter thay đổi, padding và loss đúng, deterministic reload và peak VRAM.

In [8]:
smoke_evidence = training_smoke(cfg, pairs)
display(smoke_evidence)

`torch_dtype` is deprecated! Use `dtype` instead!

{'losses': [1.8327947854995728, 1.9543851613998413],
 'gradient_norms': [0.6885833144187927, 0.6924562454223633],
 'base_unchanged': True,
 'adapter_updated': True,
 'trainable_parameters': 2359296,
 'peak_vram_bytes': 1919235584,
 'seconds': 1.5961980290012434,
 'smoke_pair_ids': ['real:f343e5c71f609b7cec5e71b71b461f8dc73e44196198a22c9b49721fda8bfa3a:0000',
  'real:cdf6d49d83f9e1110d9a2d3b071f9772f8376de9cbd62d6ccb7e22299dcd4c61:0000',
  'real:434f7a48b2e32e9f598dce7c87cbbf993167ba14ae6b5c8bcfc4add265313940:0000',
  'real:f75f9b1593437e4e7de6bc6938681be77cb8d1189ecd9c1c09e4e2bba8f7e67f:0000',
  'real:24ebf5cc09130eb9e0b5566536135f79d3d9417f1c22bd0e14710f7cf7056c31:0000',
  'real:505f72b99c909d4b21745a7e5ce16b1a2541a381ce6f816f34223e3990ae5daf:0000',
  'real:53df11ca5425ae34e92a340563a2ac716750572a10a450337824f3e0ee904383:0000',
  'real:fb8a78d74f2d42f6dff3f329526fd4e201b0b5b933cd50b9c75ec512c1289690:0000'],
 'save_reload_outputs_equal': True,
 'adapter_hashes': {'adapter_config.json': '646f687da8755fcfce145d12c941862ee0d39413c21be935f916db5f8304e3a7',
  'adapter_model.safetensors': 'aba9d15016d0448e4486e595b9488d8fa79803dcb94caaedbee1dcab2483c44f'},
 'generated_smoke_metrics': {'reference_words': 113,
  'reference_characters': 470,
  'substitutions': 8,
  'deletions': 7,
  'insertions': 8,
  'hits': 98,
  'errors': 23,
  'character_substitutions': 17,
  'character_deletions': 32,
  'character_insertions': 35,
  'character_hits': 421,
  'character_errors': 84,
  'num_samples': 4,
  'wer': 0.20353982300884957,
  'cer': 0.17872340425531916,
  'corpus_wer': 0.20353982300884957,
  'corpus_cer': 0.17872340425531916,
  'mean_sentence_wer': 0.2050766283524904,
  'median_sentence_wer': 0.2222222222222222,
  'mean_sentence_cer': 0.1785821485902278,
  'median_sentence_cer': 0.18424897720631211,
  'undefined_sentence_wer': 0,
  'undefined_sentence_cer': 0,
  'empty_reference_samples': 0,
  'insertions_on_empty_references': 0,
  'character_insertions_on_empty_references': 0,
  'raw': {'reference_words': 113,
   'reference_characters': 470,
   'substitutions': 7,
   'deletions': 7,
   'insertions': 8,
   'hits': 99,
   'errors': 22,
   'character_substitutions': 14,
   'character_deletions': 32,
   'character_insertions': 36,
   'character_hits': 424,
   'character_errors': 82,
   'num_samples': 4,
   'wer': 0.19469026548672566,
   'cer': 0.17446808510638298,
   'corpus_wer': 0.19469026548672566,
   'corpus_cer': 0.17446808510638298,
   'mean_sentence_wer': 0.19581736909323116,
   'median_sentence_wer': 0.2037037037037037,
   'mean_sentence_cer': 0.1742718037626416,
   'median_sentence_cer': 0.17562828755113968,
   'undefined_sentence_wer': 0,
   'undefined_sentence_cer': 0,
   'empty_reference_samples': 0,
   'insertions_on_empty_references': 0,
   'character_insertions_on_empty_references': 0},
  'raw_wer': 0.19469026548672566,
  'delta_wer': 0.008849557522123908,
  'raw_cer': 0.17446808510638298,
  'delta_cer': 0.004255319148936176,
  'relative_wer_reduction': -0.045454545454545456,
  'improved': 0,
  'worsened': 1,
  'tied': 3,
  'raw_string_changed': 4,
  'raw_string_change_rate': 1.0,
  'normalized_string_changed': 1,
  'normalized_string_change_rate': 0.25,
  'initially_correct_samples': 0,
  'initially_correct_worsened': 0,
  'initially_correct_worsening_rate': None,
  'preservation': {'reference_words': 0,
   'reference_characters': 0,
   'substitutions': 0,
   'deletions': 0,
   'insertions': 0,
   'hits': 0,
   'errors': 0,
   'character_substitutions': 0,
   'character_deletions': 0,
   'character_insertions': 0,
   'character_hits': 0,
   'character_errors': 0,
   'num_samples': 0,
   'wer': None,
   'cer': None,
   'corpus_wer': None,
   'corpus_cer': None,
   'mean_sentence_wer': None,
   'median_sentence_wer': None,
   'mean_sentence_cer': None,
   'median_sentence_cer': None,
   'undefined_sentence_wer': 0,
   'undefined_sentence_cer': 0,
   'empty_reference_samples': 0,
   'insertions_on_empty_references': 0,
   'character_insertions_on_empty_references': 0,
   'status': 'not_evaluated',
   'raw_string_changed': 0,
   'raw_string_change_rate': None,
   'normalized_string_changed': 0,
   'normalized_string_change_rate': None,
   'reference_overcorrection_rate': None},
  'reference_overcorrection_rate': None,
  'per_recording': {'smoke_train_only': {'reference_words': 113,
    'reference_characters': 470,
    'substitutions': 8,
    'deletions': 7,
    'insertions': 8,
    'hits': 98,
    'errors': 23,
    'character_substitutions': 17,
    'character_deletions': 32,
    'character_insertions': 35,
    'character_hits': 421,
    'character_errors': 84,
    'num_samples': 4,
    'wer': 0.20353982300884957,
    'cer': 0.17872340425531916,
    'corpus_wer': 0.20353982300884957,
    'corpus_cer': 0.17872340425531916,
    'mean_sentence_wer': 0.2050766283524904,
    'median_sentence_wer': 0.2222222222222222,
    'mean_sentence_cer': 0.1785821485902278,
    'median_sentence_cer': 0.18424897720631211,
    'undefined_sentence_wer': 0,
    'undefined_sentence_cer': 0,
    'empty_reference_samples': 0,
    'insertions_on_empty_references': 0,
    'character_insertions_on_empty_references': 0,
    'raw': {'reference_words': 113,
     'reference_characters': 470,
     'substitutions': 7,
     'deletions': 7,
     'insertions': 8,
     'hits': 99,
     'errors': 22,
     'character_substitutions': 14,
     'character_deletions': 32,
     'character_insertions': 36,
     'character_hits': 424,
     'character_errors': 82,
     'num_samples': 4,
     'wer': 0.19469026548672566,
     'cer': 0.17446808510638298,
     'corpus_wer': 0.19469026548672566,
     'corpus_cer': 0.17446808510638298,
     'mean_sentence_wer': 0.19581736909323116,
     'median_sentence_wer': 0.2037037037037037,
     'mean_sentence_cer': 0.1742718037626416,
     'median_sentence_cer': 0.17562828755113968,
     'undefined_sentence_wer': 0,
     'undefined_sentence_cer': 0,
     'empty_reference_samples': 0,
     'insertions_on_empty_references': 0,
     'character_insertions_on_empty_references': 0},
    'raw_wer': 0.19469026548672566,
    'delta_wer': 0.008849557522123908,
    'raw_cer': 0.17446808510638298,
    'delta_cer': 0.004255319148936176,
    'relative_wer_reduction': -0.045454545454545456,
    'improved': 0,
    'worsened': 1,
    'tied': 3,
    'raw_string_changed': 4,
    'raw_string_change_rate': 1.0,
    'normalized_string_changed': 1,
    'normalized_string_change_rate': 0.25,
    'initially_correct_samples': 0,
    'initially_correct_worsened': 0,
    'initially_correct_worsening_rate': None,
    'preservation': {'reference_words': 0,
     'reference_characters': 0,
     'substitutions': 0,
     'deletions': 0,
     'insertions': 0,
     'hits': 0,
     'errors': 0,
     'character_substitutions': 0,
     'character_deletions': 0,
     'character_insertions': 0,
     'character_hits': 0,
     'character_errors': 0,
     'num_samples': 0,
     'wer': None,
     'cer': None,
     'corpus_wer': None,
     'corpus_cer': None,
     'mean_sentence_wer': None,
     'median_sentence_wer': None,
     'mean_sentence_cer': None,
     'median_sentence_cer': None,
     'undefined_sentence_wer': 0,
     'undefined_sentence_cer': 0,
     'empty_reference_samples': 0,
     'insertions_on_empty_references': 0,
     'character_insertions_on_empty_references': 0,
     'status': 'not_evaluated',
     'raw_string_changed': 0,
     'raw_string_change_rate': None,
     'normalized_string_changed': 0,
     'normalized_string_change_rate': None,
     'reference_overcorrection_rate': None},
    'reference_overcorrection_rate': None}},
  'metric_policy': {'normalization': 'experiment001 NFC/lower/non-word-to-space/collapse-whitespace',
   'word_unit': 'whitespace-delimited units, usually Vietnamese syllables',
   'character_unit': 'Unicode codepoints including normalized interword spaces',
   'zero_denominator': 'null, including empty-empty; numerator counts always retained',
   'sentence_summary': 'mean/median over nonempty normalized references only',
   'delta': 'candidate minus raw; negative is improvement'}}}

## 9. Khóa recipe và full LoRA training
Không tune bằng test. Seeds 42/43/44 khởi tạo độc lập, sampler 70/30, token-weighted accumulation, dev generation mỗi epoch. Full tối đa 5 epoch, early stopping patience 2.

In [9]:
recipe_lock = lock_recipe(cfg, pairs, dev_records)
display({'recipe_signature': recipe_lock['signature'], 'locked_at': recipe_lock['locked_at']})
training_receipts = train_all(cfg, pairs, dev_records)
display(pd.DataFrame([{'run': r['run_name'], 'seed': r['seed'], 'epochs': r['completed_epochs'], 'optimizer_steps': r['actual_optimizer_steps'], 'best_checkpoint': r['best_checkpoint'], 'dev_wer': r['best_key'][0], 'peak_vram_GiB': r['peak_vram_bytes'] / 2**30} for r in training_receipts]))

{'recipe_signature': 'f47425309d20ccf15466a080a800989391b0388b567a0ba2eb7e9eec4d4741cd',
 'locked_at': '2026-09-06T10:23:55.224289+00:00'}

Verified completed R3_seed42: 1041 updates

Verified completed R3_seed43: 1041 updates

Verified completed R3_seed44: 1041 updates

,run,seed,epochs,optimizer_steps,best_checkpoint,dev_wer,peak_vram_GiB
0,R3_seed42,42,3,1041,epoch-1,0.053619,1.953755
1,R3_seed43,43,3,1041,epoch-1,0.054183,1.951381
2,R3_seed44,44,3,1041,epoch-1,0.057340,1.951381

## 10. Chọn checkpoint, NER consistency và test lock
Chọn trained candidate trên dev, không giả rằng đã review y khoa. Frozen NER chạy trên raw/corrected/reference; chỉ báo prediction consistency. Xuất blinded review và paired cluster bootstrap.

In [10]:
dev_result = selected_dev_results(cfg, dev_records, training_receipts, baseline_result)
selection = lock_final_selection(cfg, training_receipts, dev_result)
display(selection)
display({'review': dev_result['review'], 'ner_consistency': dev_result['ner']['runs'], 'auxiliary': cfg['auxiliary']})

{'selected_run': 'R3_seed42',
 'seed': 42,
 'checkpoint': 'epoch-1',
 'checkpoint_hashes': {'adapter_config.json': '3547ccd10f716824b434b28ca4024039fb353831b6734c2146f39105070a025d',
  'adapter_model.safetensors': '8a6c9ff21c125c2498e3fac0f0bde9225031cf780940ac79569a5694567cb6c7'},
 'recipe_signature': 'f47425309d20ccf15466a080a800989391b0388b567a0ba2eb7e9eec4d4741cd',
 'mode': 'full',
 'all_runs': [{'run_name': 'R3_seed42',
   'best_checkpoint': 'epoch-1',
   'best_hashes': {'adapter_config.json': '3547ccd10f716824b434b28ca4024039fb353831b6734c2146f39105070a025d',
    'adapter_model.safetensors': '8a6c9ff21c125c2498e3fac0f0bde9225031cf780940ac79569a5694567cb6c7'},
   'dev_key': [0.05361881233415683, 0.2195738533766703, 1]},
  {'run_name': 'R3_seed43',
   'best_checkpoint': 'epoch-1',
   'best_hashes': {'adapter_config.json': '3547ccd10f716824b434b28ca4024039fb353831b6734c2146f39105070a025d',
    'adapter_model.safetensors': '51e4f282a529dbf3e19716ea003d61fed4f50b407d28409a44ee61f32fe0887f'},
   'dev_key': [0.05418306035928874, 0.22571325388226796, 1]},
  {'run_name': 'R3_seed44',
   'best_checkpoint': 'epoch-1',
   'best_hashes': {'adapter_config.json': '3547ccd10f716824b434b28ca4024039fb353831b6734c2146f39105070a025d',
    'adapter_model.safetensors': '8a699084a2d7a9ab49d20579ac26c43859fe43b976cfd18967885adfc1f4b3c0'},
   'dev_key': [0.05733979931070241, 0.28494041170097506, 1]}],
 'selection_policy': {'checkpoint': 'minimum generated dev corpus WER, then preservation, then earliest epoch',
  'export_seed': 'minimum best-checkpoint dev WER, then preservation, then seed',
  'review_status': 'pending_human_review',
  'deployment': 'not_approved_without_content_review; retain R0 if quantitative criteria fail',
  'minimum_relative_wer_reduction': 0.02},
 'rulebook_signature': '3b70a8fcf98c9173ebddb708c7624411ec2fea3abdbfbad5e7a02dfaf37d0feb',
 'status': 'trained_candidate_pending_human_review',
 'dev_relative_wer_reduction': -0.20866277071158473,
 'test_used_for_selection': False,
 'signature': '3abb06b8644acdbb0248b30f9d0bb847daf360d2445e891c504d1389f6862371',
 'locked_at': '2026-09-06T11:13:17.498337+00:00'}

{'review': {'assignment': '/home/hieu/Work/Learning.UIT/VoDoCo/experiments/002-vietmed-correction-training/outputs/full/review/sample_assignment.json',
  'blinded_csv': '/home/hieu/Work/Learning.UIT/VoDoCo/experiments/002-vietmed-correction-training/outputs/full/review/blinded_review.csv',
  'blinding_key': '/home/hieu/Work/Learning.UIT/VoDoCo/experiments/002-vietmed-correction-training/outputs/full/review/blinding_key.json',
  'export_state': '/home/hieu/Work/Learning.UIT/VoDoCo/experiments/002-vietmed-correction-training/outputs/full/review/export_state.json'},
 'ner_consistency': {'R0': {'num_samples': 2769,
   'matched': 7634,
   'reference_predicted_entities': 8179,
   'candidate_predicted_entities': 8097,
   'consistency_precision': 0.9428183277757194,
   'consistency_retention': 0.9333659371561316,
   'consistency_f1': 0.9380683214549029,
   'both_entity_sets_empty_samples': 224,
   'interpretation': 'NER prediction consistency, not gold NER F1 or clinical quality',
   'zero_denominator': 'null; both-empty contributes zero entity counts'},
  'R1': {'num_samples': 2769,
   'matched': 7634,
   'reference_predicted_entities': 8179,
   'candidate_predicted_entities': 8097,
   'consistency_precision': 0.9428183277757194,
   'consistency_retention': 0.9333659371561316,
   'consistency_f1': 0.9380683214549029,
   'both_entity_sets_empty_samples': 224,
   'interpretation': 'NER prediction consistency, not gold NER F1 or clinical quality',
   'zero_denominator': 'null; both-empty contributes zero entity counts'},
  'R2': {'num_samples': 2769,
   'matched': 6678,
   'reference_predicted_entities': 8179,
   'candidate_predicted_entities': 8165,
   'consistency_precision': 0.8178812002449479,
   'consistency_retention': 0.8164812324245018,
   'consistency_f1': 0.8171806167400881,
   'both_entity_sets_empty_samples': 204,
   'interpretation': 'NER prediction consistency, not gold NER F1 or clinical quality',
   'zero_denominator': 'null; both-empty contributes zero entity counts'},
  'R3_seed42': {'num_samples': 2769,
   'matched': 7403,
   'reference_predicted_entities': 8179,
   'candidate_predicted_entities': 8031,
   'consistency_precision': 0.9218030133233719,
   'consistency_retention': 0.9051228756571708,
   'consistency_f1': 0.9133867982726712,
   'both_entity_sets_empty_samples': 220,
   'interpretation': 'NER prediction consistency, not gold NER F1 or clinical quality',
   'zero_denominator': 'null; both-empty contributes zero entity counts'},
  'R3_seed43': {'num_samples': 2769,
   'matched': 7414,
   'reference_predicted_entities': 8179,
   'candidate_predicted_entities': 8032,
   'consistency_precision': 0.9230577689243028,
   'consistency_retention': 0.9064677833475975,
   'consistency_f1': 0.9146875578311023,
   'both_entity_sets_empty_samples': 221,
   'interpretation': 'NER prediction consistency, not gold NER F1 or clinical quality',
   'zero_denominator': 'null; both-empty contributes zero entity counts'},
  'R3_seed44': {'num_samples': 2769,
   'matched': 7368,
   'reference_predicted_entities': 8179,
   'candidate_predicted_entities': 8038,
   'consistency_precision': 0.9166459318238368,
   'consistency_retention': 0.900843623914904,
   'consistency_f1': 0.9086760806561016,
   'both_entity_sets_empty_samples': 218,
   'interpretation': 'NER prediction consistency, not gold NER F1 or clinical quality',
   'zero_denominator': 'null; both-empty contributes zero entity counts'}},
 'auxiliary': {'enabled': False,
  'runs_omitted': ['R4', 'R3-budget'],
  'reason': 'No approved rights/text-review/source-group/noise manifest; R3 is independent.',
  'required_before_enable': ['rights',
   'reviewed clean targets',
   'parent/source groups',
   'train-only noise profile',
   'matched-budget R3-budget']}}

## 11. Final evaluation và diagnostic sau test lock
Chấm toàn official test, giữ riêng 143 dev_shared_recording và 85 cv_diagnostic. Không dùng diagnostic để chọn model. Báo mọi seed/run, mean/std và 2.000 paired recording-cluster bootstrap. Test đã được xem trong lịch sử.

In [11]:
test_result = final_evaluation(cfg, records_by_split, training_receipts, baseline_result['rules'])
display(pd.DataFrame([{'run': run, 'samples': report['summary']['num_samples'], 'wer': report['summary']['wer'], 'cer': report['summary']['cer'], 'relative_wer_reduction': report['summary']['relative_wer_reduction'], 'overcorrection': report['summary']['reference_overcorrection_rate']} for run, report in test_result['reports'].items()]))
display(test_result['statistics'])

,run,samples,wer,cer,relative_wer_reduction,overcorrection
0,R0,3437,0.283485,0.213638,0.000000,0.000000
1,R1,3437,0.283485,0.213638,0.000000,0.000000
2,R2,3437,0.278954,0.215046,0.015984,0.190864
3,R3_seed42,3437,0.279834,0.216006,0.012880,0.173407
4,R3_seed43,3437,0.278613,0.215186,0.017189,0.179226
5,R3_seed44,3437,0.278980,0.216417,0.015891,0.215595

{'split_name': 'test_official',
 'runs': {'R0': {'wer': 0.2834852504662586,
   'raw_wer': 0.2834852504662586,
   'delta_wer_to_R0': 0.0,
   'ci95_percentile': [0.0, 0.0],
   'defined_replicates': 2000,
   'undefined_replicates': 0,
   'cluster_errors': {'VietMed_002': 3276,
    'VietMed_004': 3781,
    'VietMed_014': 1260,
    'VietMed_015': 2274,
    'VietMed_017': 838,
    'VietMed_018': 3128,
    'VietMed_019': 979,
    'VietMed_023': 1454,
    'VietMed_024': 1459,
    'VietMed_025': 1033,
    'VietMed_026': 150,
    'VietMed_027': 605,
    'VietMed_028': 790,
    'VietMed_029': 557}},
  'R1': {'wer': 0.2834852504662586,
   'raw_wer': 0.2834852504662586,
   'delta_wer_to_R0': 0.0,
   'ci95_percentile': [0.0, 0.0],
   'defined_replicates': 2000,
   'undefined_replicates': 0,
   'cluster_errors': {'VietMed_002': 3276,
    'VietMed_004': 3781,
    'VietMed_014': 1260,
    'VietMed_015': 2274,
    'VietMed_017': 838,
    'VietMed_018': 3128,
    'VietMed_019': 979,
    'VietMed_023': 1454,
    'VietMed_024': 1459,
    'VietMed_025': 1033,
    'VietMed_026': 150,
    'VietMed_027': 605,
    'VietMed_028': 790,
    'VietMed_029': 557}},
  'R2': {'wer': 0.278954004570648,
   'raw_wer': 0.2834852504662586,
   'delta_wer_to_R0': -0.004531245895610602,
   'ci95_percentile': [-0.006083628385137394, -0.0031245341191090785],
   'defined_replicates': 2000,
   'undefined_replicates': 0,
   'cluster_errors': {'VietMed_002': 3229,
    'VietMed_004': 3762,
    'VietMed_014': 1240,
    'VietMed_015': 2226,
    'VietMed_017': 823,
    'VietMed_018': 3118,
    'VietMed_019': 968,
    'VietMed_023': 1406,
    'VietMed_024': 1420,
    'VietMed_025': 1013,
    'VietMed_026': 150,
    'VietMed_027': 586,
    'VietMed_028': 756,
    'VietMed_029': 542}},
  'R3_seed42': {'wer': 0.2798339856576217,
   'raw_wer': 0.2834852504662586,
   'delta_wer_to_R0': -0.0036512648086369486,
   'ci95_percentile': [-0.004639751372319168, -0.002914759996431303],
   'defined_replicates': 2000,
   'undefined_replicates': 0,
   'cluster_errors': {'VietMed_002': 3243,
    'VietMed_004': 3753,
    'VietMed_014': 1236,
    'VietMed_015': 2243,
    'VietMed_017': 827,
    'VietMed_018': 3108,
    'VietMed_019': 970,
    'VietMed_023': 1425,
    'VietMed_024': 1438,
    'VietMed_025': 1012,
    'VietMed_026': 148,
    'VietMed_027': 601,
    'VietMed_028': 764,
    'VietMed_029': 538}},
  'R3_seed43': {'wer': 0.27861251937271797,
   'raw_wer': 0.2834852504662586,
   'delta_wer_to_R0': -0.004872731093540676,
   'ci95_percentile': [-0.006058476579441061, -0.0038168601702688073],
   'defined_replicates': 2000,
   'undefined_replicates': 0,
   'cluster_errors': {'VietMed_002': 3240,
    'VietMed_004': 3734,
    'VietMed_014': 1229,
    'VietMed_015': 2230,
    'VietMed_017': 823,
    'VietMed_018': 3102,
    'VietMed_019': 974,
    'VietMed_023': 1398,
    'VietMed_024': 1431,
    'VietMed_025': 1010,
    'VietMed_026': 148,
    'VietMed_027': 600,
    'VietMed_028': 759,
    'VietMed_029': 535}},
  'R3_seed44': {'wer': 0.2789802726627965,
   'raw_wer': 0.2834852504662586,
   'delta_wer_to_R0': -0.004504977803462135,
   'ci95_percentile': [-0.005759205201715232, -0.003514098386476038],
   'defined_replicates': 2000,
   'undefined_replicates': 0,
   'cluster_errors': {'VietMed_002': 3225,
    'VietMed_004': 3749,
    'VietMed_014': 1236,
    'VietMed_015': 2227,
    'VietMed_017': 823,
    'VietMed_018': 3089,
    'VietMed_019': 969,
    'VietMed_023': 1425,
    'VietMed_024': 1444,
    'VietMed_025': 1011,
    'VietMed_026': 148,
    'VietMed_027': 603,
    'VietMed_028': 755,
    'VietMed_029': 537}}},
 'R3_seeds': {'runs_by_seed': {'42': 'R3_seed42',
   '43': 'R3_seed43',
   '44': 'R3_seed44'},
  'missing_protocol_seeds': [],
  'status': 'complete',
  'wer_mean': 0.2791422592310454,
  'wer_std': 0.0006266376205662309,
  'delta_wer_mean': -0.004342991235213253,
  'delta_wer_std': 0.0006266376205662374,
  'std_policy': 'sample standard deviation across seeds, ddof=1; null for fewer than two defined seeds',
  'mean_delta_ci95_percentile': [-0.0054013771723556625,
   -0.0034952979383480473],
  'mean_delta_defined_replicates': 2000,
  'resampling_policy': 'same recording draws for every seed, mean of per-seed ratios; never pooled utterances'},
 'replicates': 2000,
 'seed': 42,
 'cluster_count': 14,
 'cluster_reference_words': {'VietMed_002': 7631,
  'VietMed_004': 10575,
  'VietMed_014': 4525,
  'VietMed_015': 8458,
  'VietMed_017': 3165,
  'VietMed_018': 10710,
  'VietMed_019': 4266,
  'VietMed_023': 7414,
  'VietMed_024': 7425,
  'VietMed_025': 4118,
  'VietMed_026': 355,
  'VietMed_027': 2164,
  'VietMed_028': 3092,
  'VietMed_029': 2240},
 'delta_direction': 'candidate minus R0; negative is improvement',
 'unit': 'WER ratio, not percentage points',
 'zero_denominator': 'null; undefined resamples excluded from percentile CI and counted explicitly',
 'limitations': 'Few recording clusters limit uncertainty estimates; one-cluster bootstrap is degenerate. CI does not establish clinical safety.',
 'report_signatures': {'R0': '4367ca3538accd9ddc3c7cd4ae717dafa60054775c8d5cf31b38b4db00eea6ad',
  'R1': '59a755f566a9a3ec97b414d9a308930a59370c137ab1c16ce923bd18567d1163',
  'R2': 'c132a59e239cc987b557940f4b5ccf57b24ea3d5fb819a164a270e891d712f6c',
  'R3_seed42': 'f46010ae9f523e097776528228f076cd68432b851c1136642732a607626fb772',
  'R3_seed43': 'c088d932801ba6dfcce5bb3012160478181fb1ac55cb265bb97859baa8528dd7',
  'R3_seed44': '6ef7b578eebd533107ebd9d649c00f34c9b42595ad06cdd105087fbf2b31cd00'}}

## 12. Export, FP32 control, reload và chấm file đã giao
Kiểm tra đại số merge ở FP32 và đo sai khác BF16, không giả định hai nhánh làm tròn giống nhau. Giữ nguyên checkpoint/precision/decoder đã khóa. Merged safetensors được reload local-only, chấm lại toàn official test và NER consistency; không dùng kết quả này để chọn lại model. Demo chỉ nhận ASR text, không nhận reference.

In [12]:
export_result = export_final_model(cfg, selection, train_records)
export_evidence = read_json(Path(cfg['outputs_dir']) / 'export-verification.json')
display({'model_directory': export_result['model_directory'], 'verification': export_result['verification'], 'exported_test': {k: export_result['exported_test_summary'][k] for k in ['num_samples', 'wer', 'cer', 'reference_overcorrection_rate']}})
display(pd.DataFrame(export_evidence['demo']))

{'model_directory': '/home/hieu/Work/Learning.UIT/VoDoCo/experiments/002-vietmed-correction-training/models/final_model',
 'verification': {'adapter_vs_merged_equal': False,
  'differing_probe_ids': ['train:utt_id_train_000008'],
  'merged_vs_reloaded_equal': True,
  'probe_count': 8,
  'precision_control': {'fp32_outputs_equal': True,
   'max_abs_logit_difference': 0.000823974609375,
   'mean_abs_logit_difference': 4.0547645767219365e-05,
   'atol': 0.001,
   'rtol': 0.0001,
   'explanation': 'BF16 separately rounds base and LoRA branches; merged weights round after addition.',
   'fp32_is_diagnostic_only': True,
   'deployment_precision_unchanged': 'bf16'},
  'inference_local_files_only': True,
  'reference_passed_to_inference': False},
 'exported_test': {'num_samples': 3437,
  'wer': 0.2792429535842812,
  'cer': 0.21555587323094516,
  'reference_overcorrection_rate': 0.17951702065755018}}

,id,asr_input,corrected
0,train:utt_id_train_000001,cái gì có phải là do cái cơn khó thở hay là cò...,cái gì có phải là do cái cơn khó thở hay là cò...
1,train:utt_id_train_000002,phải mang nịt rồi phải đi châm cứu rồi cho uốn...,phải mang nịt rồi phải đi châm cứu rồi cho uốn...
2,train:utt_id_train_000003,chưa mạch máu của chúng ta vấn đề gì chưa tim ...,chưa mạch máu của chúng ta vấn đề gì chưa tim ...
3,train:utt_id_train_000004,cho tất cả những khán giả mắc những vấn đề liê...,cho tất cả những khán giả mắc những vấn đề liê...
4,train:utt_id_train_000005,bài tập nặng mạnh để hi vọng rằng nó vượt qua ...,bài tập nặng mạnh để hi vọng rằng nó vượt qua ...
5,train:utt_id_train_000006,khớp thì chúng ta thường nói tới đối tượng là ...,khớp thì chúng ta thường nói tới đối tượng là ...
6,train:utt_id_train_000007,giận nó hay đau đau cả cả ngày đêm nhưng,giận nó hay đau đau cả cả ngày đêm nhưng
7,train:utt_id_train_000008,khớp tại việt nam để sản xuất nên cái thực phẩ...,khớp tại Việt nam để sản xuất nên cái thực phẩ...

## 13. Tổng hợp, artifacts và hạn chế

- Full R3 gồm seeds 42/43/44, chọn epoch bằng generated dev WER; test không dùng để chọn seed. Early stopping là hoàn tất đúng protocol, không phải lượt bị ngắt.
- R1 không có rule đạt các ngưỡng train-only đã chốt nên output trùng R0. Không nới ngưỡng sau khi chấm test.
- Bảng R3 đo adapter; file merged có thể khác do BF16, được đo riêng trong section 12 và `outputs/full/exported-model-test.json`. Không thay thế số liệu adapter bằng số của file xuất.
- Overcorrection là tỷ lệ reference bị đổi sau scoring normalization; NER consistency không phải gold NER F1. Review con người còn pending; không có kết luận an toàn y khoa hoặc tiết kiệm công chỉnh sửa.
- Test đã được tiếp xúc trong thí nghiệm lịch sử. Chỉ có ít recording; CI cluster-bootstrap không bao phủ mọi nguồn bất định. R4/R3-budget tắt do thiếu approved auxiliary manifest.

### Artifact và chạy lại

Trong thư mục experiment: `models/full/R3_seed{42,43,44}/epoch-1/` giữ adapters đã chọn; `models/final_model/` là Transformers directory độc lập. `outputs/full/final-summary.json`, `results.csv`, `bootstrap/`, `evaluation/`, `ner/`, `review/` và `export-verification.json` giữ kết quả và provenance. Cache/split/pairs ở `datasets/derived/correction/full/` tính từ repo root.

Lệnh full ở đầu notebook kiểm tra hashes, signatures, identities và completed receipts trước khi reuse. `--mode smoke` ghi namespace riêng; không thay notebook full đã chạy. Khi chuyển máy, cần môi trường pinned, source snapshots theo `datasets/sources.json` và các checkpoint/cache tương ứng; root được cấu hình qua `VODOCO_PROJECT_ROOT`. Artifact hiện tại ghi absolute paths: có thể cần tạo namespace/cache mới khi chuyển máy, không coi việc copy folder là đã xác minh resume. Không sửa recipe-lock/test-lock để ép reuse một protocol khác. Models, datasets và output chứa text/review không tự commit/push.

In [13]:
summary = final_summary(cfg, training_receipts, dev_result, test_result, export_result)
display(pd.DataFrame(summary['metrics']))
display({'notebook': summary['notebook'], 'final_model': export_result['model_directory'], 'outputs': cfg['outputs_dir'], 'full_training_completed': summary['complete_full_training'], 'human_review': summary['human_review'], 'auxiliary': summary['auxiliary']})
if MODE == 'full':
    assert summary['complete_full_training']
    assert all(report['summary']['num_samples'] == 3437 for report in test_result['reports'].values())
assert export_result['verification']['merged_vs_reloaded_equal']
if MODE == 'full':
    display({split: read_json(Path(cfg['outputs_dir']) / 'bootstrap' / split / 'comparison.json')['R3_seeds'] for split in ['dev_tune', 'test_official']})

[
  {
    "split": "dev_tune",
    "run": "R0",
    "samples": 2769,
    "wer": 0.04436209473266844,
    "cer": 0.03577951575890975,
    "relative_wer_reduction": 0.0,
    "reference_overcorrection_rate": 0.0,
    "improved": 0,
    "worsened": 0,
    "ner_consistency_f1": 0.9380683214549029
  },
  {
    "split": "dev_tune",
    "run": "R1",
    "samples": 2769,
    "wer": 0.04436209473266844,
    "cer": 0.03577951575890975,
    "relative_wer_reduction": 0.0,
    "reference_overcorrection_rate": 0.0,
    "improved": 0,
    "worsened": 0,
    "ner_consistency_f1": 0.9380683214549029
  },
  {
    "split": "dev_tune",
    "run": "R2",
    "samples": 2769,
    "wer": 0.05247506633726782,
    "cer": 0.042811494691792545,
    "relative_wer_reduction": -0.18288071502234446,
    "reference_overcorrection_rate": 0.19934994582881907,
    "improved": 61,
    "worsened": 512,
    "ner_consistency_f1": 0.8171806167400881
  },
  {
    "split": "dev_tune",
    "run": "R3_seed42",
    "samples": 2769,
    "wer": 0.05361881233415683,
    "cer": 0.0450053856600946,
    "relative_wer_reduction": -0.20866277071158473,
    "reference_overcorrection_rate": 0.2195738533766703,
    "improved": 71,
    "worsened": 552,
    "ner_consistency_f1": 0.9133867982726712
  },
  {
    "split": "dev_tune",
    "run": "R3_seed43",
    "samples": 2769,
    "wer": 0.05418306035928874,
    "cer": 0.045408859861161645,
    "relative_wer_reduction": -0.22138191818494327,
    "reference_overcorrection_rate": 0.22571325388226796,
    "improved": 70,
    "worsened": 571,
    "ner_consistency_f1": 0.9146875578311023
  },
  {
    "split": "dev_tune",
    "run": "R3_seed44",
    "samples": 2769,
    "wer": 0.05733979931070241,
    "cer": 0.04874472691641239,
    "relative_wer_reduction": -0.29254039188724645,
    "reference_overcorrection_rate": 0.28494041170097506,
    "improved": 84,
    "worsened": 720,
    "ner_consistency_f1": 0.9086760806561016
  },
  {
    "split": "test_official",
    "run": "R0",
    "samples": 3437,
    "wer": 0.2834852504662586,
    "cer": 0.21363842601512825,
    "relative_wer_reduction": 0.0,
    "reference_overcorrection_rate": 0.0,
    "improved": 0,
    "worsened": 0,
    "ner_consistency_f1": 0.5899557637262556
  },
  {
    "split": "test_official",
    "run": "R1",
    "samples": 3437,
    "wer": 0.2834852504662586,
    "cer": 0.21363842601512825,
    "relative_wer_reduction": 0.0,
    "reference_overcorrection_rate": 0.0,
    "improved": 0,
    "worsened": 0,
    "ner_consistency_f1": 0.5899557637262556
  },
  {
    "split": "test_official",
    "run": "R2",
    "samples": 3437,
    "wer": 0.278954004570648,
    "cer": 0.2150462114102094,
    "relative_wer_reduction": 0.015984062268346925,
    "reference_overcorrection_rate": 0.1908641256910096,
    "improved": 583,
    "worsened": 298,
    "ner_consistency_f1": 0.5870811173645892
  },
  {
    "split": "test_official",
    "run": "R3_seed42",
    "samples": 3437,
    "wer": 0.2798339856576217,
    "cer": 0.2160064888651323,
    "relative_wer_reduction": 0.01287991104521868,
    "reference_overcorrection_rate": 0.17340704102414897,
    "improved": 553,
    "worsened": 315,
    "ner_consistency_f1": 0.6044223499559837
  },
  {
    "split": "test_official",
    "run": "R3_seed43",
    "samples": 3437,
    "wer": 0.27861251937271797,
    "cer": 0.21518605764150886,
    "relative_wer_reduction": 0.017188658265381764,
    "reference_overcorrection_rate": 0.17922606924643583,
    "improved": 590,
    "worsened": 296,
    "ner_consistency_f1": 0.6065497439081173
  },
  {
    "split": "test_official",
    "run": "R3_seed44",
    "samples": 3437,
    "wer": 0.2789802726627965,
    "cer": 0.21641670447694403,
    "relative_wer_reduction": 0.015891401037805782,
    "reference_overcorrection_rate": 0.21559499563572884,
    "improved": 652,
    "worsened": 358,
    "ner_consistency_f1": 0.6064302698232192
  }
]

,split,run,samples,wer,cer,relative_wer_reduction,reference_overcorrection_rate,improved,worsened,ner_consistency_f1
0,dev_tune,R0,2769,0.044362,0.035780,0.000000,0.000000,0,0,0.938068
1,dev_tune,R1,2769,0.044362,0.035780,0.000000,0.000000,0,0,0.938068
2,dev_tune,R2,2769,0.052475,0.042811,-0.182881,0.199350,61,512,0.817181
3,dev_tune,R3_seed42,2769,0.053619,0.045005,-0.208663,0.219574,71,552,0.913387
4,dev_tune,R3_seed43,2769,0.054183,0.045409,-0.221382,0.225713,70,571,0.914688
5,dev_tune,R3_seed44,2769,0.057340,0.048745,-0.292540,0.284940,84,720,0.908676
6,test_official,R0,3437,0.283485,0.213638,0.000000,0.000000,0,0,0.589956
7,test_official,R1,3437,0.283485,0.213638,0.000000,0.000000,0,0,0.589956
8,test_official,R2,3437,0.278954,0.215046,0.015984,0.190864,583,298,0.587081
9,test_official,R3_seed42,3437,0.279834,0.216006,0.012880,0.173407,553,315,0.604422
10,test_official,R3_seed43,3437,0.278613,0.215186,0.017189,0.179226,590,296,0.606550
11,test_official,R3_seed44,3437,0.278980,0.216417,0.015891,0.215595,652,358,0.606430

{'notebook': '/home/hieu/Work/Learning.UIT/VoDoCo/experiments/002-vietmed-correction-training/train_correction_end_to_end.ipynb',
 'final_model': '/home/hieu/Work/Learning.UIT/VoDoCo/experiments/002-vietmed-correction-training/models/final_model',
 'outputs': '/home/hieu/Work/Learning.UIT/VoDoCo/experiments/002-vietmed-correction-training/outputs/full',
 'full_training_completed': True,
 'human_review': 'pending; no clinical safety claim',
 'auxiliary': {'enabled': False,
  'runs_omitted': ['R4', 'R3-budget'],
  'reason': 'No approved rights/text-review/source-group/noise manifest; R3 is independent.',
  'required_before_enable': ['rights',
   'reviewed clean targets',
   'parent/source groups',
   'train-only noise profile',
   'matched-budget R3-budget']}}

{'dev_tune': {'runs_by_seed': {'42': 'R3_seed42',
   '43': 'R3_seed43',
   '44': 'R3_seed44'},
  'missing_protocol_seeds': [],
  'status': 'complete',
  'wer_mean': 0.055047224001382664,
  'wer_std': 0.0020053728132552384,
  'delta_wer_mean': 0.010685129268714226,
  'delta_wer_std': 0.002005372813255238,
  'std_policy': 'sample standard deviation across seeds, ddof=1; null for fewer than two defined seeds',
  'mean_delta_ci95_percentile': [0.008927211099268865, 0.011889405365500209],
  'mean_delta_defined_replicates': 2000,
  'resampling_policy': 'same recording draws for every seed, mean of per-seed ratios; never pooled utterances'},
 'test_official': {'runs_by_seed': {'42': 'R3_seed42',
   '43': 'R3_seed43',
   '44': 'R3_seed44'},
  'missing_protocol_seeds': [],
  'status': 'complete',
  'wer_mean': 0.2791422592310454,
  'wer_std': 0.0006266376205662309,
  'delta_wer_mean': -0.004342991235213253,
  'delta_wer_std': 0.0006266376205662374,
  'std_policy': 'sample standard deviation across seeds, ddof=1; null for fewer than two defined seeds',
  'mean_delta_ci95_percentile': [-0.0054013771723556625,
   -0.0034952979383480473],
  'mean_delta_defined_replicates': 2000,
  'resampling_policy': 'same recording draws for every seed, mean of per-seed ratios; never pooled utterances'}}